//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservation_id { get; set; }
        public int bus_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> date_of_journey { get; set; }
        public Nullable<int> total_fare { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual User_details User_details { get; set; }
    }
}
